/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as ContactUsIndexRouteImport } from './routes/contact-us/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as SearchJobsRouteImport } from './routes/search/jobs'
import { Route as SearchCandidatesRouteImport } from './routes/search/candidates'
import { Route as OnboardingSeekerRouteImport } from './routes/onboarding/seeker'
import { Route as OnboardingEmployerRouteImport } from './routes/onboarding/employer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsIndexRoute = ContactUsIndexRouteImport.update({
  id: '/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchJobsRoute = SearchJobsRouteImport.update({
  id: '/search/jobs',
  path: '/search/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchCandidatesRoute = SearchCandidatesRouteImport.update({
  id: '/search/candidates',
  path: '/search/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSeekerRoute = OnboardingSeekerRouteImport.update({
  id: '/onboarding/seeker',
  path: '/onboarding/seeker',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingEmployerRoute = OnboardingEmployerRouteImport.update({
  id: '/onboarding/employer',
  path: '/onboarding/employer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding/employer': typeof OnboardingEmployerRoute
  '/onboarding/seeker': typeof OnboardingSeekerRoute
  '/search/candidates': typeof SearchCandidatesRoute
  '/search/jobs': typeof SearchJobsRoute
  '/auth/': typeof AuthIndexRoute
  '/contact-us/': typeof ContactUsIndexRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding/employer': typeof OnboardingEmployerRoute
  '/onboarding/seeker': typeof OnboardingSeekerRoute
  '/search/candidates': typeof SearchCandidatesRoute
  '/search/jobs': typeof SearchJobsRoute
  '/auth': typeof AuthIndexRoute
  '/contact-us': typeof ContactUsIndexRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding/employer': typeof OnboardingEmployerRoute
  '/onboarding/seeker': typeof OnboardingSeekerRoute
  '/search/candidates': typeof SearchCandidatesRoute
  '/search/jobs': typeof SearchJobsRoute
  '/auth/': typeof AuthIndexRoute
  '/contact-us/': typeof ContactUsIndexRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding/employer'
    | '/onboarding/seeker'
    | '/search/candidates'
    | '/search/jobs'
    | '/auth/'
    | '/contact-us/'
    | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding/employer'
    | '/onboarding/seeker'
    | '/search/candidates'
    | '/search/jobs'
    | '/auth'
    | '/contact-us'
    | '/home'
  id:
    | '__root__'
    | '/'
    | '/onboarding/employer'
    | '/onboarding/seeker'
    | '/search/candidates'
    | '/search/jobs'
    | '/auth/'
    | '/contact-us/'
    | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingEmployerRoute: typeof OnboardingEmployerRoute
  OnboardingSeekerRoute: typeof OnboardingSeekerRoute
  SearchCandidatesRoute: typeof SearchCandidatesRoute
  SearchJobsRoute: typeof SearchJobsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  ContactUsIndexRoute: typeof ContactUsIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us/': {
      id: '/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us/'
      preLoaderRoute: typeof ContactUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/jobs': {
      id: '/search/jobs'
      path: '/search/jobs'
      fullPath: '/search/jobs'
      preLoaderRoute: typeof SearchJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/candidates': {
      id: '/search/candidates'
      path: '/search/candidates'
      fullPath: '/search/candidates'
      preLoaderRoute: typeof SearchCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/seeker': {
      id: '/onboarding/seeker'
      path: '/onboarding/seeker'
      fullPath: '/onboarding/seeker'
      preLoaderRoute: typeof OnboardingSeekerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/employer': {
      id: '/onboarding/employer'
      path: '/onboarding/employer'
      fullPath: '/onboarding/employer'
      preLoaderRoute: typeof OnboardingEmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingEmployerRoute: OnboardingEmployerRoute,
  OnboardingSeekerRoute: OnboardingSeekerRoute,
  SearchCandidatesRoute: SearchCandidatesRoute,
  SearchJobsRoute: SearchJobsRoute,
  AuthIndexRoute: AuthIndexRoute,
  ContactUsIndexRoute: ContactUsIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
